# Generated by Django 5.1.3 on 2025-12-19 22:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telegram_id', models.BigIntegerField(help_text='Уникальный идентификатор пользователя в Telegram', unique=True, verbose_name='Telegram ID')),
                ('username_telegram', models.CharField(blank=True, help_text='Имя пользователя в Telegram', max_length=150, null=True, verbose_name='Telegram Username')),
                ('first_name_telegram', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя в Telegram')),
                ('last_name_telegram', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия в Telegram')),
                ('total_games', models.PositiveIntegerField(default=0, verbose_name='Всего игр')),
                ('games_won', models.PositiveIntegerField(default=0, verbose_name='Побед')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='Общий счет')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Текущая серия побед')),
                ('best_streak', models.PositiveIntegerField(default=0, verbose_name='Лучшая серия побед')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Уведомления включены')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=10, verbose_name='Язык')),
                ('date_joined_telegram', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации в Telegram')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='telegram_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='telegram_users', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
                'ordering': ['-total_points', '-date_joined_telegram'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
