# Generated by Django 5.1.3 on 2025-12-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='Уникальный идентификатор пользователя в Telegram', null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
