# Generated by Django 5.1.3 on 2025-12-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_telegramuser_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='coins',
            field=models.PositiveIntegerField(default=100, help_text='Обычная валюта для покупок', verbose_name='Монеты'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='gold',
            field=models.PositiveIntegerField(default=0, help_text='Премиум валюта для особых покупок', verbose_name='Золото'),
        ),
    ]
