# Generated by Django 5.1.3 on 2025-12-19 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('rarity', models.CharField(choices=[('common', 'Обычный'), ('uncommon', 'Необычный'), ('rare', 'Редкий'), ('epic', 'Эпический'), ('legendary', 'Легендарный')], default='common', max_length=20, verbose_name='Редкость')),
                ('item_type', models.CharField(choices=[('consumable', 'Расходуемый'), ('equipment', 'Экипировка'), ('collectible', 'Коллекционный'), ('currency', 'Валюта'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип предмета')),
                ('coin_cost', models.PositiveIntegerField(default=0, verbose_name='Стоимость в монетах')),
                ('gold_cost', models.PositiveIntegerField(default=0, verbose_name='Стоимость в золоте')),
                ('max_stack', models.PositiveIntegerField(default=1, help_text='Максимальное количество предметов в одной ячейке', verbose_name='Максимум в стопке')),
                ('is_stackable', models.BooleanField(default=True, help_text='Можно ли складывать несколько предметов в одну ячейку', verbose_name='Можно складывать')),
                ('is_active', models.BooleanField(default=True, help_text='Доступен ли предмет для получения', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('acquired_at', models.DateTimeField(auto_now_add=True, verbose_name='Получен')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Предмет в инвентаре',
                'verbose_name_plural': 'Предметы в инвентаре',
                'ordering': ['-acquired_at'],
                'unique_together': {('player', 'item')},
            },
        ),
    ]
