# Generated by Django 5.1.3 on 2025-12-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(verbose_name='Правильный ответ')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='Заработанные очки')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Время ответа')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='Номер раунда')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начался')),
                ('time_limit_seconds', models.PositiveIntegerField(default=60, verbose_name='Время на ответ (секунды)')),
            ],
            options={
                'verbose_name': 'Раунд игры',
                'verbose_name_plural': 'Раунды игры',
                'ordering': ['game_session', 'round_number'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание игроков'), ('active', 'Активная'), ('finished', 'Завершена'), ('cancelled', 'Отменена')], default='waiting', max_length=20, verbose_name='Статус')),
                ('max_players', models.PositiveIntegerField(default=4, verbose_name='Максимум игроков')),
                ('time_limit', models.PositiveIntegerField(default=30, verbose_name='Время на игру (минуты)')),
                ('points_for_win', models.PositiveIntegerField(default=100, verbose_name='Очки за победу')),
                ('telegram_chat_id', models.BigIntegerField(verbose_name='Telegram Chat ID')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram Message ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начата')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
            ],
            options={
                'verbose_name': 'Игровая сессия',
                'verbose_name_plural': 'Игровые сессии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerInGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Присоединился')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Очки в игре')),
                ('is_ready', models.BooleanField(default=False, verbose_name='Готов к игре')),
            ],
            options={
                'verbose_name': 'Игрок в игре',
                'verbose_name_plural': 'Игроки в играх',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=10, verbose_name='Сложность')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('correct_answer', models.TextField(verbose_name='Правильный ответ')),
                ('times_asked', models.PositiveIntegerField(default=0, verbose_name='Количество показов')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Правильных ответов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-created_at'],
            },
        ),
    ]
