# Generated by Django 5.1.3 on 2025-12-19 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Игрок'),
        ),
        migrations.AddField(
            model_name='answer',
            name='game_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.gameround', verbose_name='Раунд игры'),
        ),
        migrations.AddField(
            model_name='gameround',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.gamesession', verbose_name='Игровая сессия'),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_in_game', to='game.gamesession', verbose_name='Игровая сессия'),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Игрок'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='players',
            field=models.ManyToManyField(through='game.PlayerInGame', to=settings.AUTH_USER_MODEL, verbose_name='Игроки'),
        ),
        migrations.AddField(
            model_name='gameround',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.question', verbose_name='Вопрос'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('player', 'game_round')},
        ),
        migrations.AlterUniqueTogether(
            name='playeringame',
            unique_together={('player', 'game_session')},
        ),
        migrations.AlterUniqueTogether(
            name='gameround',
            unique_together={('game_session', 'round_number')},
        ),
    ]
