# Generated by Django 5.1.3 on 2025-12-19 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название карты')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image_url', models.URLField(blank=True, verbose_name='URL изображения')),
                ('anime_universe', models.CharField(help_text='Название аниме или франшизы', max_length=100, verbose_name='Аниме-вселенная')),
                ('season', models.CharField(help_text='Сезон или арка аниме', max_length=50, verbose_name='Сезон')),
                ('rarity', models.CharField(choices=[('common', 'Обычная'), ('rare', 'Редкая'), ('epic', 'Эпическая'), ('legendary', 'Легендарная'), ('mythic', 'Мифическая')], default='common', max_length=20, verbose_name='Редкость')),
                ('element', models.CharField(choices=[('fire', 'Огонь'), ('water', 'Вода'), ('earth', 'Земля'), ('air', 'Воздух'), ('light', 'Свет'), ('dark', 'Тьма'), ('neutral', 'Нейтральная')], default='neutral', max_length=20, verbose_name='Стихия')),
                ('health_min', models.PositiveIntegerField(default=100, verbose_name='Мин. здоровье')),
                ('health_max', models.PositiveIntegerField(default=100, verbose_name='Макс. здоровье')),
                ('attack_min', models.PositiveIntegerField(default=10, verbose_name='Мин. атака')),
                ('attack_max', models.PositiveIntegerField(default=10, verbose_name='Макс. атака')),
                ('defense_min', models.PositiveIntegerField(default=5, verbose_name='Мин. защита')),
                ('defense_max', models.PositiveIntegerField(default=5, verbose_name='Макс. защита')),
                ('coin_cost', models.PositiveIntegerField(default=10, verbose_name='Стоимость в монетах')),
                ('gold_cost', models.PositiveIntegerField(default=0, verbose_name='Стоимость в золоте')),
                ('is_active', models.BooleanField(default=True, help_text='Доступна ли карта для получения', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Шаблон карты',
                'verbose_name_plural': 'Шаблоны карт',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'anime_universe', 'season')},
            },
        ),
        migrations.CreateModel(
            name='CardInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.PositiveIntegerField(verbose_name='Здоровье')),
                ('attack', models.PositiveIntegerField(verbose_name='Атака')),
                ('defense', models.PositiveIntegerField(verbose_name='Защита')),
                ('current_health', models.PositiveIntegerField(verbose_name='Текущее здоровье')),
                ('is_in_deck', models.BooleanField(default=False, help_text='Используется ли карта в текущей колоде игрока', verbose_name='В колоде')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Уровень')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Опыт')),
                ('acquired_at', models.DateTimeField(auto_now_add=True, verbose_name='Получена')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_instances', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardtemplate', verbose_name='Шаблон карты')),
            ],
            options={
                'verbose_name': 'Карта игрока',
                'verbose_name_plural': 'Карты игроков',
                'ordering': ['-acquired_at'],
            },
        ),
    ]
