# Generated by Django 5.1.3 on 2025-12-19 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeUniverse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название вселенной')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('logo_url', models.URLField(blank=True, verbose_name='URL логотипа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Аниме-вселенная',
                'verbose_name_plural': 'Аниме-вселенные',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='cardtemplate',
            name='rarity',
        ),
        migrations.AddField(
            model_name='cardtemplate',
            name='sell_price',
            field=models.PositiveIntegerField(default=5, help_text='Цена продажи карты игроку в монетах', verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='cardtemplate',
            name='anime_universe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.animeuniverse', verbose_name='Аниме-вселенная'),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сезона')),
                ('season_number', models.PositiveIntegerField(verbose_name='Номер сезона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('anime_universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='cards.animeuniverse', verbose_name='Аниме-вселенная')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
                'ordering': ['anime_universe', 'season_number'],
                'unique_together': {('anime_universe', 'season_number')},
            },
        ),
        migrations.AlterField(
            model_name='cardtemplate',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.season', verbose_name='Сезон'),
        ),
    ]
