# Generated by Django 5.1.3 on 2025-12-19 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_animeuniverse_remove_cardtemplate_rarity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название колоды')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=False, help_text='Используется ли эта колода в текущих боях', verbose_name='Активная колода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Колоды',
                'verbose_name_plural': 'Колоды',
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Порядок карты в колоде (1-3)', verbose_name='Позиция в колоде')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardinstance', verbose_name='Карта')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_cards', to='cards.deck', verbose_name='Колоды')),
            ],
            options={
                'verbose_name': 'Карта в колоде',
                'verbose_name_plural': 'Карты в колодах',
                'ordering': ['position'],
                'unique_together': {('deck', 'card')},
            },
        ),
    ]
