# Generated by Django 5.1.3 on 2025-12-19 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_deck_deckcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deck',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(default='Моя колода', max_length=50, verbose_name='Название колоды'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.RemoveField(
            model_name='deck',
            name='is_active',
        ),
    ]
